// Prototype option lists for low-friction onboarding selectors.

import 'mock_opportunities.dart';

/// Derived from the mock job catalog rather than a hand-typed parallel
/// list — keeps employment-form suggestions in sync with the app's real
/// mock companies instead of drifting into a second, fictional set.
final mockCompanyNames = mockOpportunities.map((o) => o.company).toSet().toList()..sort();

/// Same reasoning as [mockCompanyNames] — sourced from real listing titles.
final mockJobTitles = mockOpportunities.map((o) => o.title).toSet().toList()..sort();

/// Same reasoning again — every requirement string across the real mock
/// catalog, flattened and deduped, as a skills-suggestion pool.
final mockSkills = mockOpportunities.expand((o) => o.requirements).toSet().toList()..sort();

/// Interested-roles/industries options — shared by onboarding's Goals
/// screen, Profile Edit, and the college Home opportunity filter's
/// category picker. Was independently duplicated in two of those three
/// places before being pulled out here; a third copy would have made that
/// drift risk worse instead of better. Single words only, on purpose (see
/// goals_screen.dart's own note on this) — 'Consulting' has no matching
/// Opportunity.category in the mock catalog (only 11 categories exist
/// there), so picking it as a filter choice yields zero results, same as
/// it already silently does today wherever it's picked as an onboarding
/// role.
const mockAllRoles = [
  'Software', 'Data', 'Marketing', 'Finance', 'Design', 'Product',
  'Content', 'Sales', 'Operations', 'HR', 'Consulting', 'Research',
];

const mockCities = [
  'Agra',
  'Ahmedabad',
  'Aizawl',
  'Ajmer',
  'Aligarh',
  'Allahabad (Prayagraj)',
  'Amritsar',
  'Aurangabad',
  'Bareilly',
  'Belagavi',
  'Bengaluru',
  'Bhavnagar',
  'Bhopal',
  'Bhubaneswar',
  'Bikaner',
  'Chandigarh',
  'Chennai',
  'Coimbatore',
  'Cuttack',
  'Dehradun',
  'Delhi',
  'Dhanbad',
  'Durgapur',
  'Faridabad',
  'Gandhinagar',
  'Ghaziabad',
  'Goa (Panaji)',
  'Gorakhpur',
  'Greater Noida',
  'Guntur',
  'Gurugram',
  'Guwahati',
  'Gwalior',
  'Hubballi',
  'Hyderabad',
  'Imphal',
  'Indore',
  'Jabalpur',
  'Jaipur',
  'Jalandhar',
  'Jammu',
  'Jamshedpur',
  'Jodhpur',
  'Kanpur',
  'Kochi',
  'Kohima',
  'Kolhapur',
  'Kolkata',
  'Kota',
  'Kozhikode',
  'Lucknow',
  'Ludhiana',
  'Madurai',
  'Mangaluru',
  'Meerut',
  'Mumbai',
  'Mysuru',
  'Nagpur',
  'Nashik',
  'Navi Mumbai',
  'Noida',
  'Patna',
  'Pondicherry (Puducherry)',
  'Pune',
  'Raipur',
  'Rajkot',
  'Ranchi',
  'Rourkela',
  'Salem',
  'Shimla',
  'Siliguri',
  'Srinagar',
  'Surat',
  'Thane',
  'Thiruvananthapuram',
  'Thrissur',
  'Tiruchirappalli',
  'Tirupati',
  'Udaipur',
  'Vadodara',
  'Varanasi',
  'Vellore',
  'Vijayawada',
  'Visakhapatnam',
  'Warangal',
];

/// Major colleges & universities across India (search + type any name if missing).
const mockColleges = [
  'ABES Engineering College',
  'Acharya Narendra Dev College',
  'Ahmedabad University',
  'AIIMS Bhopal',
  'AIIMS Delhi',
  'AIIMS Jodhpur',
  'Ajay Kumar Garg Engineering College',
  'Aligarh Muslim University',
  'Ambedkar University Delhi',
  'Amity University Greater Noida',
  'Amity University Gurugram',
  'Amity University Jaipur',
  'Amity University Lucknow',
  'Amity University Mumbai',
  'Amity University Noida',
  'Amrita School of Engineering',
  'Amrita Vishwa Vidyapeetham',
  'Andhra University',
  'Andhra University College of Engineering',
  'Anna University',
  'Anna University Affiliated College',
  'Ansal University',
  'Anurag University',
  'Arya College of Engineering',
  'Ashoka University',
  'Ashoka University Sonipat',
  'Assam University',
  'Atma Ram Sanatan Dharma College',
  'Azim Premji University',
  'Babu Banarasi Das University',
  'Banaras Hindu University',
  'Banaras Hindu University Affiliated College',
  'Bangalore University',
  'Bennett University',
  'Bhaskaracharya College of Applied Sciences',
  'BIT Mesra',
  'BIT Sindri',
  'BITS Goa',
  'BITS Hyderabad',
  'BITS Pilani',
  'BITS Pilani Goa Campus',
  'BML Munjal University',
  'BMS College of Engineering',
  'BMS Institute of Technology',
  'BPIT Delhi',
  'Calicut University',
  'CBIT Hyderabad',
  'CCET Chandigarh',
  'Central University of Jharkhand',
  'Central University of Kashmir',
  'Central University of Rajasthan',
  'CEPT University',
  'CET Bhubaneswar',
  'Chandigarh Group of Colleges',
  'Chandigarh University',
  'Chitkara University',
  'Chitkara University Himachal',
  'Christ University',
  'Christ University Bannerghatta',
  'Cluster University Srinagar',
  'CMC Vellore',
  'CMR Institute of Technology',
  'Cochin University of Science and Technology',
  'COEP Technological University',
  'College of Engineering Guindy',
  'CVR College of Engineering',
  'DAIICT Gandhinagar',
  'Daulat Ram College',
  'DAV University',
  'Dayananda Sagar College of Engineering',
  'DCRUST Murthal',
  'Deen Dayal Upadhyaya College',
  'Deenbandhu Chhotu Ram University of Science and Technology',
  'Delhi University',
  'Dev Bhoomi Uttarakhand University',
  'DIT University',
  'DIT University Dehradun',
  'DJ Sanghvi College of Engineering',
  'Dr. A.P.J. Abdul Kalam Technical University',
  'DTU Delhi',
  'Flame University',
  'FMS Delhi',
  'Fr. Conceicao Rodrigues College of Engineering',
  'FTII Pune',
  'Galgotias College of Engineering and Technology',
  'Galgotias University',
  'Gargi College',
  'Gauhati University',
  'GB Pant University of Agriculture and Technology',
  'GD Goenka University',
  'GITAM University',
  'GL Bajaj Institute of Technology and Management',
  'Global Institute of Technology Jaipur',
  'Goa University',
  'Gokaraju Rangaraju Institute of Engineering and Technology',
  'Graphic Era Hill University',
  'Graphic Era University',
  'GTU (Gujarat Technological University)',
  'Gujarat University',
  'Guru Jambheshwar University',
  'Guru Nanak Dev Engineering College',
  'Guru Nanak Dev University',
  'Hansraj College',
  'Harcourt Butler Technical University',
  'Heritage Institute of Technology',
  'Himachal Pradesh University',
  'Hindu College Delhi',
  'Hindustan Institute of Technology and Science',
  'Hindustan University',
  'HMR Institute of Technology and Management',
  'HNB Garhwal University',
  'IARI Delhi',
  'ICFAI University Hyderabad',
  'ICT Mumbai',
  'IGDTUW Delhi',
  'IGNOU',
  'IIFT Delhi',
  'IIIT Agartala',
  'IIIT Allahabad',
  'IIIT Bangalore',
  'IIIT Bhagalpur',
  'IIIT Bhopal',
  'IIIT Delhi',
  'IIIT Guwahati',
  'IIIT Gwalior',
  'IIIT Hyderabad',
  'IIIT Kalyani',
  'IIIT Kota',
  'IIIT Kottayam',
  'IIIT Lucknow',
  'IIIT Nagpur',
  'IIIT Pune',
  'IIIT Ranchi',
  'IIIT Sri City',
  'IIIT Surat',
  'IIIT Una',
  'IIIT Vadodara',
  'IIITD&M Kancheepuram',
  'IIM Ahmedabad',
  'IIM Bangalore',
  'IIM Calcutta',
  'IIM Indore',
  'IIM Kozhikode',
  'IIM Lucknow',
  'IISc Bangalore',
  'IIT (BHU) Affiliated College',
  'IIT (BHU) Varanasi',
  'IIT (ISM) Dhanbad',
  'IIT Bhilai',
  'IIT Bhubaneswar',
  'IIT Bombay',
  'IIT Delhi',
  'IIT Dharwad',
  'IIT Gandhinagar',
  'IIT Goa',
  'IIT Guwahati',
  'IIT Hyderabad',
  'IIT Indore',
  'IIT Jammu',
  'IIT Jodhpur',
  'IIT Kanpur',
  'IIT Kharagpur',
  'IIT Madras',
  'IIT Mandi',
  'IIT Palakkad',
  'IIT Patna',
  'IIT Roorkee',
  'IIT Ropar',
  'IIT Tirupati',
  'IK Gujral Punjab Technical University',
  'IMS Engineering College',
  'IMT Ghaziabad',
  'Institute of Engineering and Management Kolkata',
  'Integral University',
  'International Institute of Information Technology Bangalore',
  'IP College for Women',
  'ISB Hyderabad',
  'ISB Mohali',
  'ITER Bhubaneswar',
  'IVRI Bareilly',
  'Jadavpur University',
  'Jadavpur University Affiliated College',
  'Jain University',
  'Jamia Millia Islamia',
  'Jawaharlal Nehru University',
  'Jaypee Institute of Information Technology',
  'Jaypee University Anoopshahr',
  'Jaypee University of Information Technology',
  'Jaypee University of Information Technology Waknaghat',
  'JBIMS Mumbai',
  'JC Bose University of Science and Technology',
  'JECRC Foundation',
  'JECRC University',
  'Jesus and Mary College',
  'JIIT Noida',
  'JNTU Anantapur',
  'JNTU Hyderabad',
  'JNTU Kakinada',
  'JNVU Jodhpur',
  'JSS Academy of Technical Education',
  'K L University',
  'K.R. Mangalam University',
  'Kakatiya University',
  'Kalasalingam University',
  'Karunya University',
  'Kerala University',
  'Keshav Mahavidyalaya',
  'KIET Group of Institutions',
  'KIIT University',
  'Kirori Mal College',
  'KJ Somaiya College of Engineering',
  'Kumaun University',
  'Kurukshetra University',
  'Lady Shri Ram College',
  'LNMIIT Jaipur',
  'Lovely Professional University',
  'Lovely Professional University Phagwara',
  'Maharaja Agrasen College',
  'Maharaja Surajmal Institute of Technology',
  'Maharshi Dayanand University',
  'Mahatma Gandhi University Kottayam',
  'Mahindra University',
  'Manav Rachna University',
  'Manipal Institute of Technology',
  'Manipal University Jaipur',
  'Manipur University',
  'MDI Gurgaon',
  'MDS University Ajmer',
  'MDU Rohtak Affiliated College',
  'MICA Ahmedabad',
  'Miranda House',
  'MIT ADT University',
  'MIT WPU Pune',
  'Mizoram University',
  'MLR Institute of Technology',
  'Modi Institute of Technology',
  'Mohanlal Sukhadia University',
  'Motilal Nehru College',
  'Motilal Nehru National Institute of Technology',
  'Mount Carmel College',
  'MS Ramaiah Institute of Technology',
  'Mysore University',
  'Nagaland University',
  'NALSAR Hyderabad',
  'National Institute of Design',
  'NDRI Karnal',
  'New Horizon College of Engineering',
  'NID Ahmedabad',
  'NIFT Bengaluru',
  'NIFT Delhi',
  'NIFT Mumbai',
  'Nirma University',
  'NIT Agartala',
  'NIT Allahabad (MNNIT)',
  'NIT Andhra Pradesh',
  'NIT Arunachal Pradesh',
  'NIT Bhopal (MANIT)',
  'NIT Calicut',
  'NIT Delhi',
  'NIT Durgapur',
  'NIT Goa',
  'NIT Hamirpur',
  'NIT Jaipur (MNIT)',
  'NIT Jalandhar',
  'NIT Jamshedpur',
  'NIT Kurukshetra',
  'NIT Kurukshetra Affiliated College',
  'NIT Manipur',
  'NIT Meghalaya',
  'NIT Mizoram',
  'NIT Nagaland',
  'NIT Nagpur (VNIT)',
  'NIT Patna',
  'NIT Patna Affiliated College',
  'NIT Puducherry',
  'NIT Raipur',
  'NIT Rourkela',
  'NIT Sikkim',
  'NIT Silchar',
  'NIT Silchar Affiliated College',
  'NIT Srinagar',
  'NIT Srinagar Affiliated College',
  'NIT Surathkal',
  'NIT Trichy',
  'NIT Uttarakhand',
  'NIT Warangal',
  'Nitte Meenakshi Institute of Technology',
  'NLSIU Bangalore',
  'NLU Delhi',
  'NMIMS Mumbai',
  'Noida Institute of Engineering and Technology',
  'North-Eastern Hill University',
  'NSUT Delhi',
  'OP Jindal Global University',
  'OP Jindal University',
  'Osmania University',
  'Osmania University Affiliated College',
  'Panjab University',
  'Panjab University Affiliated College',
  'Patna University',
  'PAU Ludhiana',
  'PDEU Gandhinagar',
  'PES University',
  'Pondicherry University',
  'Poornima College of Engineering',
  'Poornima University',
  'Presidency University Kolkata',
  'PSG College of Technology',
  'Punjab Engineering College',
  'Punjab Technical University',
  'Punjab University Regional Centre',
  'Quantum University',
  'Rajalakshmi Engineering College',
  'Rajasthan Technical University',
  'Rajdhani College',
  'Ramjas College',
  'Ranchi University',
  'REVA University',
  'RV College of Engineering',
  'RV University',
  'Sastra University',
  'Sathyabama Institute of Science and Technology',
  'Saveetha Engineering College',
  'Savitribai Phule Pune University',
  'SCMHRD Pune',
  'SGT University',
  'Shaheed Sukhdev College of Business Studies',
  'Sharda University',
  'Shiv Nadar University',
  'Shoolini University',
  'SIBM Pune',
  'Sikkim University',
  'SKIT Jaipur',
  'SMVDU Katra',
  'SOA University',
  'South Asian University',
  'SP Jain Institute of Management and Research',
  'SPIT Mumbai',
  'SRCC Delhi',
  'Sri Venkateswara College Delhi',
  'Sri Venkateswara University',
  'SRKR Engineering College',
  'SRM Institute of Science and Technology',
  'SRM University AP',
  'SRM University Sonepat',
  'SRM Valliammai Engineering College',
  'SSN College of Engineering',
  'St. Joseph\'s College Bangalore',
  'St. Stephen\'s College Delhi',
  'St. Xavier\'s College Kolkata',
  'St. Xavier\'s College Mumbai',
  'Symbiosis Institute of Technology',
  'Symbiosis International University',
  'Tamil Nadu Agricultural University',
  'Tezpur University',
  'Thapar Institute of Engineering and Technology',
  'Thapar University',
  'The NorthCap University',
  'Thiagarajar College of Engineering',
  'TISS Hyderabad',
  'TISS Mumbai',
  'Tripura University',
  'UIET Chandigarh',
  'University of Agricultural Sciences Bangalore',
  'University of Allahabad',
  'University of Calcutta',
  'University of Hyderabad',
  'University of Jammu',
  'University of Kashmir',
  'University of Kota',
  'University of Ladakh',
  'University of Lucknow',
  'University of Madras',
  'University of Mumbai',
  'University of Petroleum and Energy Studies',
  'University of Rajasthan',
  'UPES Dehradun',
  'Uttaranchal University',
  'Vasavi College of Engineering',
  'Vel Tech Rangarajan Dr. Sagunthala R&D Institute',
  'VIT AP',
  'VIT Bhopal',
  'VIT Chennai',
  'VIT Vellore',
  'Vivekananda College Delhi',
  'VJTI Mumbai',
  'VTU Belagavi',
  'Woxsen University',
  'Xavier Institute of Engineering',
  'XIMB Bhubaneswar',
  'XLRI Jamshedpur',
  'YMCA Faridabad',
  'YMCA University of Science and Technology',
  'Zakir Husain Delhi College',
];

/// Course / degree options grouped by level for faster picking.
const mockCourseUndergraduate = [
  'B.Tech',
  'B.E.',
  'B.Sc',
  'B.Com',
  'BBA',
  'BA',
  'BCA',
  'B.Des',
  'B.Arch',
  'B.Pharm',
  'BDS',
  'MBBS',
  'LLB',
  'BA LLB',
  'B.Ed',
  'BHM',
  'BJMC',
];

const mockCoursePostgraduate = [
  'M.Tech',
  'M.E.',
  'MBA',
  'M.Sc',
  'MCA',
  'M.Com',
  'MA',
  'LLM',
  'M.Des',
  'M.Arch',
  'M.Pharm',
  'MD',
  'MS',
  'Integrated M.Tech',
];

const mockCourseOther = [
  'Diploma',
  'PG Diploma',
  'Certificate',
  'PhD',
  'M.Phil',
];

const mockCourses = [
  ...mockCourseUndergraduate,
  ...mockCoursePostgraduate,
  ...mockCourseOther,
];

/// Expected annual salary — banded ranges (Naukri's own pattern) instead
/// of asking for an exact figure most students wouldn't know how to answer.
const mockSalaryRanges = [
  'Less than 3 LPA',
  '3-5 LPA',
  '5-7 LPA',
  '7-10 LPA',
  '10-15 LPA',
  '15-20 LPA',
  '20-30 LPA',
  '30+ LPA',
];

/// Specialization within a degree (distinct from the degree type itself,
/// e.g. course = "B.Tech", field of study = "Computer Science").
/// Languages Known — English plus every major Indian language, including
/// the classical/rare ones (Sanskrit, Kashmiri, Maithili, Konkani, Sindhi).
/// Deliberately no foreign languages (French, German, etc.) — this app's
/// audience and every language surface in it are India-only.
const mockLanguages = [
  'English',
  'Hindi',
  'Bengali',
  'Marathi',
  'Telugu',
  'Tamil',
  'Gujarati',
  'Urdu',
  'Kannada',
  'Odia',
  'Malayalam',
  'Punjabi',
  'Assamese',
  'Maithili',
  'Sanskrit',
  'Kashmiri',
  'Konkani',
  'Sindhi',
];

const mockFieldsOfStudy = [
  'Computer Science',
  'Information Technology',
  'Electronics & Communication',
  'Electrical Engineering',
  'Mechanical Engineering',
  'Civil Engineering',
  'Chemical Engineering',
  'Biotechnology',
  'Data Science',
  'Artificial Intelligence & Machine Learning',
  'Business Administration',
  'Finance',
  'Marketing',
  'Human Resources',
  'Economics',
  'Accounting',
  'Psychology',
  'Sociology',
  'English Literature',
  'Political Science',
  'Journalism & Mass Communication',
  'Fine Arts',
  'Architecture',
  'Law',
  'Pharmacy',
  'Physiotherapy',
  'Nursing',
  'Hospitality Management',
  'Fashion Design',
  'Graphic Design',
];

/// Semester-select options for college/UG onboarding + Edit Profile —
/// covers every real program length (4-year UG at 8, 5-year integrated at
/// 10, ...) with one flat list, same as the year-based version it replaces
/// needed no per-segment branching either.
const mockSemesters = [
  'Semester 1', 'Semester 2', 'Semester 3', 'Semester 4',
  'Semester 5', 'Semester 6', 'Semester 7', 'Semester 8',
  'Semester 9', 'Semester 10', 'Semester 11', 'Semester 12',
  'Semester 13', 'Semester 14', 'Semester 15', 'Semester 16',
];
